
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const ApiKeyInput = lazy(() => import("./pages/ApiKeyInput.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ChatApp = lazy(() => import("./pages/ChatApp.tsx"));
const LoadingScreen = lazy(() => import("./pages/LoadingScreen.tsx"));
const LocationInput = lazy(() => import("./pages/LocationInput.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/api-key-input", element: <ApiKeyInput />},
	{ path: "/apikeyinput", element: <ApiKeyInput />},
	{ path: "/", element: <App />},
	{ path: "/chat-app", element: <ChatApp />},
	{ path: "/chatapp", element: <ChatApp />},
	{ path: "/loading-screen", element: <LoadingScreen />},
	{ path: "/loadingscreen", element: <LoadingScreen />},
	{ path: "/location-input", element: <LocationInput />},
	{ path: "/locationinput", element: <LocationInput />},

];
